// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx81vS641Sx26t_y1P4EOAdPFxT4wJgg',
    appId: '1:1050128185147:web:6eaa71dfbf11dff717691e',
    messagingSenderId: '1050128185147',
    projectId: 'flash-chat-e0005',
    authDomain: 'flash-chat-e0005.firebaseapp.com',
    storageBucket: 'flash-chat-e0005.appspot.com',
    measurementId: 'G-LG308QF06E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bu58TjyCyr9uiCeR-c9QwCYkjx2LMik',
    appId: '1:1050128185147:android:01a50245e7727b1c17691e',
    messagingSenderId: '1050128185147',
    projectId: 'flash-chat-e0005',
    storageBucket: 'flash-chat-e0005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOiFGS3dYyf1pjlCzm7q6RV07IOkiNL8',
    appId: '1:1050128185147:ios:709982485379e84017691e',
    messagingSenderId: '1050128185147',
    projectId: 'flash-chat-e0005',
    storageBucket: 'flash-chat-e0005.appspot.com',
    iosClientId: '1050128185147-161im3p9ros57vksurg53njo5p83epce.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
